CREATE DATABASE DbGestionEventos;
GO

USE DbGestionEventos;

CREATE TABLE PROVINCIA(
	ID_PROVINCIA INT IDENTITY(1,1),
	NOMBRE VARCHAR(30),
	CONSTRAINT PK_PROVINCIA PRIMARY KEY(ID_PROVINCIA)
);

CREATE TABLE PROVEEDOR(
	ID_PROVEEDOR UNIQUEIDENTIFIER DEFAULT NEWID(),
	NOMBRE VARCHAR(50) NOT NULL,
	APELLIDO VARCHAR(30) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	DNI BIGINT UNIQUE NOT NULL,
	TELEFONO VARCHAR(10),
	ID_PROVINCIA INT NOT NULL,
	DIRECCION VARCHAR(100),
	PUNTAJE DECIMAL(4,2) DEFAULT 5.00,
	[PASSWORD] VARCHAR(64) NOT NULL,
	CONSTRAINT PK_PROVEEDOR PRIMARY KEY(ID_PROVEEDOR),
	CONSTRAINT FK_PROVEEDOR_PROVINCIA FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIA(ID_PROVINCIA)
);


CREATE TABLE ORGANIZADOR(
	ID_ORGANIZADOR UNIQUEIDENTIFIER DEFAULT NEWID(),
	NOMBRE VARCHAR(50) NOT NULL,
	APELLIDO VARCHAR(30) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	DNI BIGINT UNIQUE NOT NULL,
	TELEFONO VARCHAR(10),
	ID_PROVINCIA INT NOT NULL,
	DIRECCION VARCHAR(100),
	[PASSWORD] VARCHAR(64) NOT NULL,
	CONSTRAINT PK_ORGANIZADOR PRIMARY KEY(ID_ORGANIZADOR),
	CONSTRAINT FK_ORGANIZADOR_PROVINCIA FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIA(ID_PROVINCIA)
);

CREATE TABLE SERVICIO(
	ID_SERVICIO INT IDENTITY(1,1),
	CATEGORIA VARCHAR(20) NOT NULL,
	DESCRIPCION VARCHAR(100) NOT NULL,
	CONSTRAINT PK_SERVICIO PRIMARY KEY (ID_SERVICIO)
);

CREATE TABLE SERVICIO_PUBLICADO(
	ID_SERV_PUB UNIQUEIDENTIFIER DEFAULT NEWID(),
	FECHA_PUBLICACION DATETIME NOT NULL,
	NOMBRE VARCHAR(30) NOT NULL,
	DESCRIPCION VARCHAR (255),
	ID_PROVEEDOR UNIQUEIDENTIFIER NOT NULL,
	ID_SERVICIO INT NOT NULL,
	PRECIO DECIMAL(8,2) NOT NULL,
	ENVIO BIT DEFAULT 0,
	FIN_DE_SEMANA BIT NOT NULL,
	ENTRE_SEMANA BIT NOT NULL,
	CANT_SERV_DIARIOS INT NOT NULL,
	CONSTRAINT CHK_PRECIO CHECK(PRECIO > 0),
	CONSTRAINT PK_SERVICIO_PUBLICADO PRIMARY KEY(ID_SERV_PUB),
	CONSTRAINT FK_SERVICIO_PUBLICADO_PROVEEDOR FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR(ID_PROVEEDOR),
	CONSTRAINT FK_SERVICIO_PUBLICADO_SERVICIO FOREIGN KEY(ID_SERVICIO)REFERENCES SERVICIO(ID_SERVICIO)
);

CREATE TABLE FECHA_RESERVADA(
	ID_SERV_PUB UNIQUEIDENTIFIER NOT NULL,
	FECHA DATETIME NOT NULL,
	CANT_RESERVAS INT NOT NULL,
	CONSTRAINT PK_FECHA_RESERVADA PRIMARY KEY(ID_SERV_PUB, FECHA),
	CONSTRAINT FK_FECHA_RESERVADA_SERVICIO_PUBLICADO FOREIGN KEY(ID_SERV_PUB) REFERENCES SERVICIO_PUBLICADO(ID_SERV_PUB)
);

CREATE TABLE EVENTO(
	ID_EVENTO UNIQUEIDENTIFIER DEFAULT NEWID(),
	ID_ORGANIZADOR UNIQUEIDENTIFIER NOT NULL,
	NOMBRE VARCHAR(30)NOT NULL,
	DESCRIPCION VARCHAR(255) NOT NULL,
	FECHA_HORA DATETIME NOT NULL,
	ID_PROVINCIA INT, 
	DIRECCION VARCHAR(100),
	CANT_INVITADOS INT NOT NULL,
	CONSTRAINT PK_EVENTO PRIMARY KEY(ID_EVENTO),
	CONSTRAINT FK_EVENTO_ORGANIZADOR FOREIGN KEY(ID_ORGANIZADOR) REFERENCES ORGANIZADOR(ID_ORGANIZADOR),
	CONSTRAINT FK_EVENTO_PROVINCIA FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIA(ID_PROVINCIA)
);

CREATE TABLE EVENTO_PROVEEDOR_SERVICIO(
	ID_EVENTO UNIQUEIDENTIFIER NOT NULL,
	ID_PROVEEDOR UNIQUEIDENTIFIER NOT NULL,
	ID_SERVICIO INT NOT NULL,
	CANTIDAD INT NOT NULL, 
	PRECIO_UNITARIO DECIMAL(8,2) NOT NULL,
	MONTO_TOTAL DECIMAL(8,2) NOT NULL,
	PAGO BIT DEFAULT 0,
	FECHA_PAGO DATETIME DEFAULT NULL,
	COMPLETADO BIT DEFAULT 0,
	CONSTRAINT PK_EVENTO_PROVEEDOR_SERVICIO PRIMARY KEY(ID_EVENTO,ID_PROVEEDOR, ID_SERVICIO),
	CONSTRAINT FK_EVENTO_PROVEEDOR_SERVICIO_EVENTO FOREIGN KEY(ID_EVENTO) REFERENCES EVENTO(ID_EVENTO),
	CONSTRAINT FK_EVENTO_PROVEEDOR_SERVICIO_PROVEEDOR FOREIGN KEY(ID_PROVEEDOR) REFERENCES PROVEEDOR(ID_PROVEEDOR),
	CONSTRAINT FK_EVENTO_PROVEEDOR_SERVICIO_SERVICIO FOREIGN KEY(ID_SERVICIO) REFERENCES SERVICIO(ID_SERVICIO)
);

CREATE TABLE INVITADO(
	ID_EVENTO UNIQUEIDENTIFIER NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	APELLIDO VARCHAR(30) NOT NULL,
	CANT_COMPANIONS INT NOT NULL DEFAULT 0,
	CONSTRAINT PK_INVITADO PRIMARY KEY(ID_EVENTO, EMAIL),
	CONSTRAINT FK_INVITADO_EVENTO FOREIGN KEY(ID_EVENTO) REFERENCES EVENTO(ID_EVENTO)
);