//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbGestionEventos : DbContext
    {
        public DbGestionEventos()
            : base("name=DbGestionEventos")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CREDENCIALES> CREDENCIALES { get; set; }
        public virtual DbSet<EVENTO> EVENTO { get; set; }
        public virtual DbSet<EVENTO_PROVEEDOR_SERVICIO> EVENTO_PROVEEDOR_SERVICIO { get; set; }
        public virtual DbSet<FECHA_RESERVADA> FECHA_RESERVADA { get; set; }
        public virtual DbSet<INVITADO> INVITADO { get; set; }
        public virtual DbSet<ORGANIZADOR> ORGANIZADOR { get; set; }
        public virtual DbSet<PAGO> PAGO { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public virtual DbSet<PROVINCIA> PROVINCIA { get; set; }
        public virtual DbSet<SERVICIO> SERVICIO { get; set; }
        public virtual DbSet<SERVICIO_PUBLICADO> SERVICIO_PUBLICADO { get; set; }
    }
}
