//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FECHA_RESERVADA
    {
        public System.Guid ID_SERV_PUB { get; set; }
        public System.DateTime FECHA { get; set; }
        public int CANT_RESERVAS { get; set; }
    
        public virtual SERVICIO_PUBLICADO SERVICIO_PUBLICADO { get; set; }
    }
}
