//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVITADO
    {
        public System.Guid ID_EVENTO { get; set; }
        public string EMAIL { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public int CANT_COMPANIONS { get; set; }
    
        public virtual EVENTO EVENTO { get; set; }
    }
}
