//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGO
    {
        public Nullable<System.Guid> ID_PAGO { get; set; }
        public System.Guid ID_EVENTO { get; set; }
        public System.Guid ID_PROVEEDOR { get; set; }
        public int ID_SERVICIO { get; set; }
        public System.DateTime FECHA_PAGO { get; set; }
        public Nullable<decimal> MONTO { get; set; }
    
        public virtual EVENTO EVENTO { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        public virtual SERVICIO SERVICIO { get; set; }
    }
}
