//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIO_PUBLICADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERVICIO_PUBLICADO()
        {
            this.FECHA_RESERVADA = new HashSet<FECHA_RESERVADA>();
        }
    
        public System.Guid ID_SERV_PUB { get; set; }
        public System.DateTime FECHA_PUBLICACION { get; set; }
        public string NOMBRE { get; set; }
        public string DESCRIPCION { get; set; }
        public System.Guid ID_PROVEEDOR { get; set; }
        public int ID_SERVICIO { get; set; }
        public decimal PRECIO { get; set; }
        public Nullable<bool> ENVIO { get; set; }
        public bool FIN_DE_SEMANA { get; set; }
        public bool ENTRE_SEMANA { get; set; }
        public int CANT_SERV_DIARIOS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FECHA_RESERVADA> FECHA_RESERVADA { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        public virtual SERVICIO SERVICIO { get; set; }
    }
}
